const insuranceData = [ 
  {
    orderNo: 1,
    caseNo: '294ß2',
    workshop: 'Easy Car',
    partDealer: 'Nora Zentrum Wob.',
    currentStatus: 'In Bearbeitung',
    process: 'Kalkulation erstellt',
    date: "12/06/22",
    },
  { jobId: 2,
    orderNo: 2,
    caseNo: '29842',
    workshop: 'Auto Papa Repair Shop',
    partDealer: 'Emil Frey',
    currentStatus: 'In Bearbeitung',
    process: 'Kalkulation erstellt',
    date: "12/06/22",
  },
  { jobId: 3,
    orderNo: 3,
    caseNo: '29876',
    workshop: 'Ostermann',
    partDealer: 'Bleker Hannover',
    currentStatus: 'In Bearbeitung',
    process: 'Teile bestellt',
    date: "12/06/22",
  },
  { jobId: 4,
    orderNo: 4,
    caseNo: '29763',
    workshop: 'Lack & Repair Shop',
    partDealer: 'Brass Gruppe',
    currentStatus: 'In Bearbeitung',
    process: 'Teile bestellt',
    date: "12/06/22",
  },
  { jobId: 5,
    orderNo: 5,
    caseNo: '29873',
    workshop: 'Unfallschaden Meier',
    partDealer: 'Autohaus Schmid',
    currentStatus: 'In Bearbeitung',
    process: 'Teile in Lieferung',
    date: "12/06/22",
  },
  { jobId: 6,
    orderNo: 6,
    caseNo: '29783',
    workshop: 'Lehnnart&Sohn',
    partDealer: 'OTS',
    currentStatus: 'In Bearbeitung',
    process: 'Teile in Lieferung',
    date: "12/06/22",
  },
  { jobId: 7,
    orderNo: 7,
    caseNo: '29675',
    workshop: 'Jonas&Co GmbH',
    partDealer: 'Autohaus Niebel',
    currentStatus: 'In Bearbeitung',
    process: 'Kalkulation erstellt',
    date: "12/06/22",
  },
  { jobId: 8,
    orderNo: 8,
    caseNo: '29731',
    workshop: 'Otto K&L OHG',
    partDealer: 'EFA',
    currentStatus: 'In Bearbeitung',
    process: 'Teile bestellt',
    date: "12/06/22",
  },
  { jobId: 9,
    orderNo: 9,
    caseNo: '28302',
    workshop: 'Klaus & Klaus',
    partDealer: 'PSA Retail',
    currentStatus: 'In Bearbeitung',
    process: 'Teile bestellt',
    date: "12/06/22",
  },
  { jobId: 10,
    orderNo: 10,
    caseNo: '29992',
    workshop: 'Lackiererei Ulf',
    partDealer: 'Euler',
    currentStatus: 'In Bearbeitung',
    process: 'Kalkulation erstellt',
    date: "12/06/22",
  }
];

export default insuranceData;
